config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'hospitals/:slug', to: 'pages#show'
  get 'hospitals/:hospital_slug/doctors/:slug', to: 'pages#doctor'
  get 'auth/:provider/callback', to: 'sessions#callback'
  get 'auth/failure', to: redirect('/')

  resources :pages do
    collection do
      resources :bookings do
        collection do
          get 'my', to: 'pages#my_bookings'
        end
      end
    end
  end
  namespace :admin do
    resources :users
    resources :hospitals do
      resources :doctors do
        resources :schedules
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital
  has_many :schedules
  
  def select_by(day)
    schedules.select {|s| s.day == day.strftime('%A').downcase}
  end

  def slug
    [id, name.parameterize].join('-')
  end
end

app/controllers/admin/doctors_controller.rb
module Admin
  class DoctorsController < ApplicationController
    before_action :set_doctor, only: [:edit, :update, :destroy]
    before_action :set_hospital
    before_action :admin_authorized

    # GET /doctors
    # GET /doctors.json
    def index
      @doctors = Doctor.where(hospital: @hospital)
    end

    # GET /doctors/1
    # GET /doctors/1.json
    def show
      # @schedule = Schedule.find_by(doctor: @doctor)
      @doctor = Doctor.includes(:schedules).find_by(id: params[:id])
    end

    # GET /doctors/new
    def new
      @doctor = Doctor.new
      @hospitals = Hospital.all
    end

    # GET /doctors/1/edit
    def edit
    end

    # POST /doctors
    # POST /doctors.json
    def create
      @doctor = Doctor.new(doctor_params)
      @doctor.hospital = @hospital

      respond_to do |format|
        if @doctor.save
          format.html { redirect_to [:admin, @hospital, @doctor], notice: 'Doctor was successfully created.' }
          format.json { render :show, status: :created, location: [@hospital, @doctor] }
        else
          format.html { render :new }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /doctors/1
    # PATCH/PUT /doctors/1.json
    def update
      respond_to do |format|
        if @doctor.update(doctor_params)
          format.html { redirect_to [:admin, @doctor], notice: 'Doctor was successfully updated.' }
          format.json { render :show, status: :ok, location: @doctor }
        else
          format.html { render :edit }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /doctors/1
    # DELETE /doctors/1.json
    def destroy
      @doctor.destroy
      respond_to do |format|
        format.html { redirect_to admin_hospital_doctors_url(@hospital), notice: 'Doctor was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_doctor
        @doctor = Doctor.find(params[:id])
      end
    
      def set_hospital
        @hospital = Hospital.find(params[:hospital_id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def doctor_params
        params.require(:doctor).permit(:name, :speciality)
      end
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/admin/doctors/_form.html.erb
<%= form_with(model: doctor, url: [:admin, @hospital, doctor], local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :speciality %>
    <%= form.text_field :speciality %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', [@hospital, @doctor] %> |
<%= link_to 'Back', hospital_doctors_path(@hospital) %>

app/views/admin/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speciality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.speciality %></td>
        <td><%= link_to 'Show', [:admin, @hospital, doctor] %></td>
        <td><%= link_to 'Edit', edit_admin_hospital_doctor_path(@hospital, doctor) %></td>
        <td><%= link_to 'Destroy', [:admin, @hospital, doctor], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_admin_hospital_doctor_path %> |
<%= link_to 'Back', admin_hospital_path(@hospital) %>

app/views/admin/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', admin_hospital_doctors_path %>

app/views/admin/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Speciality:</strong>
  <%= @doctor.speciality %>
</p>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctor.schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.day %></td>
        <td><%= schedule.start_time %></td>
        <td><%= schedule.end_time %></td>
        <td><%= link_to 'Show', admin_hospital_doctor_schedule_path(@hospital, @doctor, schedule) %></td>
        <td><%= link_to 'Edit', edit_admin_hospital_doctor_schedule_path(@hospital, @doctor, schedule) %></td>
        <td><%= link_to 'Destroy', [:admin, @hospital, @doctor, schedule], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Schedule', new_admin_hospital_doctor_schedule_path(@hospital, @doctor) %> |
<%= link_to 'Edit', edit_admin_hospital_doctor_path(@hospital, @doctor) %> |
<%= link_to 'Back', admin_hospital_doctors_path %>