config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'hospitals/:slug', to: 'pages#show'
  get 'hospitals/:hospital_slug/doctors/:slug', to: 'pages#doctor'
  get 'auth/:provider/callback', to: 'sessions#callback'
  get 'auth/failure', to: redirect('/')

  resources :pages do
    collection do
      resources :bookings do
        collection do
          get 'my', to: 'pages#my_bookings'
        end
      end
    end
  end
  namespace :admin do
    resources :users
    resources :hospitals do
      resources :doctors do
        resources :schedules
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors
  belongs_to :city

  class << self
    def search(keyword)
      where("LOWER(name) LIKE '%#{keyword.downcase}%'")
    end
  end

  def slug
    [id, name.parameterize].join('-')
  end
end

app/controllers/admin/hospitals_controller.rb
module Admin
  class HospitalsController < ApplicationController
    before_action :set_hospital, only: [:show, :edit, :update, :destroy]
    before_action :admin_authorized

    # GET /hospitals
    # GET /hospitals.json
    def index
      @hospitals = Hospital.all
    end

    # GET /hospitals/1
    # GET /hospitals/1.json
    def show
    end

    # GET /hospitals/new
    def new
      @hospital = Hospital.new
    end

    # GET /hospitals/1/edit
    def edit
    end

    # POST /hospitals
    # POST /hospitals.json
    def create
      @hospital = Hospital.new(hospital_params)

      respond_to do |format|
        if @hospital.save
          format.html { redirect_to [:admin, @hospital], notice: 'Hospital was successfully created.' }
          format.json { render :show, status: :created, location: @hospital }
        else
          format.html { render :new }
          format.json { render json: @hospital.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /hospitals/1
    # PATCH/PUT /hospitals/1.json
    def update
      respond_to do |format|
        if @hospital.update(hospital_params)
          format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
          format.json { render :show, status: :ok, location: @hospital }
        else
          format.html { render :edit }
          format.json { render json: @hospital.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /hospitals/1
    # DELETE /hospitals/1.json
    def destroy
      @hospital.destroy
      respond_to do |format|
        format.html { redirect_to admin_hospitals_url, notice: 'Hospital was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_hospital
        @hospital = Hospital.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def hospital_params
        params.require(:hospital).permit(:name, :city_id)
      end
  end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/admin/hospitals/_form.html.erb
<%= form_with(model: [:admin, hospital], local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
        <% hospital.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.select :city_id, City.all.sort{|a, b| a.name <=> b.name}.map{|c| [c.name, c.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/admin/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= link_to 'Show', admin_hospital_path(hospital) %></td>
        <td><%= link_to 'Edit', edit_admin_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', admin_hospital_path(hospital), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_admin_hospital_path %>

app/views/admin/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', admin_hospitals_path %>

app/views/admin/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>

<%= link_to 'Edit', edit_admin_hospital_path(@hospital) %> |
<%= link_to 'Doctors', admin_hospital_doctors_path(@hospital) %> |
<%= link_to 'Back', admin_hospitals_path %>