config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'hospitals/:slug', to: 'pages#show'
  get 'hospitals/:hospital_slug/doctors/:slug', to: 'pages#doctor'
  get 'auth/:provider/callback', to: 'sessions#callback'
  get 'auth/failure', to: redirect('/')

  resources :pages do
    collection do
      resources :bookings do
        collection do
          get 'my', to: 'pages#my_bookings'
        end
      end
    end
  end
  namespace :admin do
    resources :users
    resources :hospitals do
      resources :doctors do
        resources :schedules
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  # enum day: [:sunday, :monday, :thuesday, :wednesday, :tuesday, :friday, :saturday]
  enum day: {sunday: 0, monday: 1, thuesday: 2, wednesday: 3, tuesday: 4, friday: 5, saturday: 6}

  belongs_to :doctor

  def doctor_name
    self.doctor.name
  end
end

app/controllers/admin/schedules_controller.rb
module Admin
  class SchedulesController < ApplicationController
    before_action :set_schedule, only: [:show, :edit, :update, :destroy]
    before_action :set_hospital
    before_action :set_doctor
    before_action :admin_authorized

    # GET /schedules
    # GET /schedules.json
    def index
      @schedules = Schedule.where(doctor: @doctor)
    end

    # GET /schedules/1
    # GET /schedules/1.json
    def show
    end

    # GET /schedules/new
    def new
      @schedule = Schedule.new
    end

    # GET /schedules/1/edit
    def edit
    end

    # POST /schedules
    # POST /schedules.json
    def create
      @schedule = Schedule.new(schedule_params)
      @schedule.doctor = @doctor

      respond_to do |format|
        if @schedule.save
          format.html { redirect_to admin_hospital_doctor_schedules_path, notice: 'Schedule was successfully created.' }
          format.json { render :show, status: :created, location: @schedule }
        else
          format.html { render :new }
          format.json { render json: @schedule.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /schedules/1
    # PATCH/PUT /schedules/1.json
    def update
      respond_to do |format|
        if @schedule.update(schedule_params)
          format.html { redirect_to [:admin, @hospital, @doctor, @schedule], notice: 'Schedule was successfully updated.' }
          format.json { render :show, status: :ok, location: @schedule }
        else
          format.html { render :edit }
          format.json { render json: @schedule.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /schedules/1
    # DELETE /schedules/1.json
    def destroy
      @schedule.destroy
      respond_to do |format|
        format.html { redirect_to admin_hospital_doctor_schedules_path, notice: 'Schedule was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_schedule
        @schedule = Schedule.find(params[:id])
      end
    
      def set_hospital
        @hospital = Hospital.find(params[:hospital_id])
      end

      def set_doctor
        @doctor = Doctor.find(params[:doctor_id])
      end
      # Never trust parameters from the scary internet, only allow the white list through.
      def schedule_params
        params.require(:schedule).permit(:doctor_id, :day, :start_time, :end_time)
      end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/admin/schedules/_form.html.erb
<%= form_with(model: schedule, url: [:admin, @hospital, @doctor, schedule], local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day %>
    <%= form.select :day, Schedule.days.map {|key, value| [key.humanize, key]} %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.text_field :start_time, ignore_date: true %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.text_field :end_time, ignore_date: true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', [:admin, @hospital, @doctor, @schedule] %> |
<%= link_to 'Back', admin_hospital_doctor_schedules_path %>

app/views/admin/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>
<h3><%= @hospital.name %></h3>
<h3><%= @doctor.name %></h3>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.day %></td>
        <td><%= schedule.start_time %></td>
        <td><%= schedule.end_time %></td>
        <td><%= link_to 'Show', admin_hospital_doctor_schedule_path(@hospital, @doctor, schedule) %></td>
        <td><%= link_to 'Edit', edit_admin_hospital_doctor_schedule_path(@hospital, @doctor, schedule) %></td>
        <td><%= link_to 'Destroy', [:admin, @hospital, @doctor, schedule], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_admin_hospital_doctor_schedule_path %>
<%= link_to 'Back', admin_hospital_doctor_path(@hospital, @doctor) %>

app/views/admin/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', admin_hospital_doctor_schedules_path %>

app/views/admin/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @schedule.doctor_id %>
</p>

<p>
  <strong>Day:</strong>
  <%= @schedule.day %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<%= link_to 'Edit', edit_admin_hospital_doctor_schedule_path(@schedule) %> |
<%= link_to 'Back', admin_hospital_doctor_schedules_path %>